project:
  type: website
  output-dir: docs

website:
  title: "Quarto"
  image: "quarto.png"
  open-graph: true
  twitter-card: true
  site-url: https://quarto.org
  repo-url: https://github.com/quarto-dev/quarto-web
  repo-actions: [edit, issue]
  page-navigation: true
  search:
    type: overlay
    algolia:
      index-name: prod_QUARTO
      application-id: ZPJB5I1QN7
      search-only-api-key: 41be6c1e0a7fea4a51b107810facf577
      analytics-events: true
      show-logo: true
  page-footer:
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: docs/faq/index.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
  navbar:
    left:
      - about.qmd
      - index.qmd
      - publications.qmd
      - skills.qmd
      - acomplishments.qmd
      - experience.qmd
      - talks.qmd
      - contact.qmd
      - icon: github
        href: https://github.com/
      - icon: instagram
        href: https://twitter.com
        
    background: light
    logo: quarto.png
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg

format:
  html:
    theme: cosmo
    css: styles.css
    #monofont: arial


editor: visual

