project:
  type: website
  output-dir: docs

website:
  title: "Chernoff Faces"
  navbar:
    right:
      - about.qmd
      - index.qmd
      - publications.qmd
      - skills.qmd
      - acomplishments.qmd
      - experience.qmd
      - talks.qmd
      - contact.qmd
      - icon: github
        href: https://github.com/
      - icon: instagram
        href: https://twitter.com
format:
  html:
    theme: litera
    css: styles.css

editor: visual

