project:
  type: website
  output-dir: docs

website:
  title: "Quarto"
  image: "quarto.png"
  open-graph: true
  twitter-card: true
  site-url: https://maltehueckstaedt.github.io/Quarto_Blog_CF/
  repo-url: https://github.com/maltehueckstaedt/Quarto_Blog_CF
  repo-actions: [issue]
  page-navigation: true
  search:
    type: overlay
  page-footer:
    left: |
      Supported by
      [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center:
      - text: "About"
        href: about.qmd
      - text: "FAQ"
        href: faq.qmd
      - text: "License"
        href: license.qmd
  navbar:
    left:
      - index.qmd
      - publications.qmd
      - skills.qmd
      - acomplishments.qmd
      - experience.qmd
      - talks.qmd
      - about.qmd
      - contact.qmd
      - icon: github
        href: https://github.com/maltehueckstaedt
      - icon: instagram
        href: https://www.instagram.com/chernoff_faces/
        
    background: light
    logo: quarto.png
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg

format:
  html:
    mermaid:
      theme: forest
    theme: cosmo
    css: styles.css
    #monofont: arial


editor: visual