project:
  type: website
  output-dir: docs

website:
  title: "Quarto"
  image: "quarto.png"
  open-graph: true
  twitter-card: true
  site-url: https://maltehueckstaedt.github.io/Quarto_Blog_CF/
  repo-url: https://github.com/maltehueckstaedt/Quarto_Blog_CF
  repo-actions: [issue]
  page-navigation: true
  search:
    type: overlay
  page-footer:
    left: |
      Supported by
      [![](https://www.rstudio.com/assets/img/posit-logo-fullcolor-TM.svg){fig-alt="Posit" width=65px}](https://posit.co)
    center:
      - text: "About"
        href: index.qmd
      - text: "FAQ"
        href: faq.qmd
      - text: "License"
        href: license.qmd
      - text: "Imprint"
        href: imprint.qmd
  navbar:
    left:
      - index.qmd
      - publications.qmd
      - recent.qmd
      - software.qmd
      - href: https://maltehueckstaedt.github.io/Quarto_Blog_CF/
        text: "{{< iconify exploding-head >}}|"
      - skills.qmd
      - acomplishments.qmd
      - experience.qmd
      - talks.qmd
    right:
      - href: https://github.com/MalteHueckstaedt?tab=repositories
        text: "{{< iconify exploding-head >}} GH"
      - href: https://orcid.org/0000-0002-0185-4230
        text: "{{< iconify exploding-head >}} ORCID"
      - href: https://scholar.google.com/citations?hl=en&user=EJTHqH4AAAAJ
        text: "{{< iconify exploding-head >}} GS"
      - href: https://www.researchgate.net/profile/Malte-Hueckstaedt
        text: "{{< iconify exploding-head >}} RS"
      - href: https://de.linkedin.com/in/malte-hückstädt-82aa78208
        text: "{{< iconify exploding-head >}} LI"

    background: light
    logo: quarto.png
    logo-alt: "Quarto logo."
    title: false
    collapse-below: lg

format:
  html:
    mermaid:
      theme: forest
    theme: cosmo
    css: 
    - styles.css
    - academicons.css
    #monofont: arial


editor: visual