---
title: "Publications"
toc: true
---

## Journal Artikel (Peer Reviewed)

-   **Hückstädt, M.** (2023). 'Ten reasons why research collaborations succeed---a random forest approach', Scientometrics, 128/3: 1923--50. DOI: <https://doi.org/10.1007/s11192-022-04629-7>

-   Weinmann, C., **Hückstädt, M**., Meißner, F., & Vowe, G. (2023). 'How do researchers perceive problems in research collaboration? Results from a large-scale study of German scientists', Frontiers in Research Metrics and Analytics, 8. DOI: <https://doi.org/10.3389/frma.2023.1106482>

-   **Hückstädt, M**., Leisten, L.M. (2023). *Input, process, output - inhibitors and promoters of collaboration Problems* (under Review).

-   **Hückstädt, M.** (2022). 'Coopetition between frenemies--interrelations and effects of seven collaboration problems in research clusters', Scientometrics, 127/9: 5191--224. DOI: 10.1007/s11192-022-04472-w. DOI: <https://doi.org/10.1007/s11192-022-04472-w>

-   Kleimann, B., & **Hückstädt, M.** (2021). *Selection criteria in professorial recruiting as indicators of institutional similarity? A comparison of German universities and universities of applied sciences*.Quality in Higher Education (online first). <https://doi.org/10.1080/13538322.2021.1889760>

-   Kleimann, B., & **Hückstädt, M**. (2018). *Auswahlkriterien in Berufungsverfahren: Universitäten und Fachhochschulen im Vergleich.* Beiträge zur Hochschulforschung, 40 (2/2018), 20-47.

## Articles in edited anthologies

-   **Hückstädt, M.** (2019). *Determinanten der subjektiv wahrgenommenen Wichtigkeit von Hochschulrankings bei der Studienortwahl?* In L. Ringel & T. Werron (Hrsg.), Rankings - Soziologische Fallstudien (S. 181-202). Wiesbaden: Springer. <https://doi.org/10.1007/978-3-658-26366-9_8>

## Workingpaper

-   **Hückstädt, M**., Janßen, M., Oberschelp, A., Wagner, N., Weinmann, C. & Winde, M. (2022). Forschungskooperation im Verbund: Herausforderungen, Lösungsansätze, Empfehlungen. Stifterverband für die Deutsche Wissenschaft. Future Lab: Kooperationsgovernance -- Diskussionspapier 6.

## Reports

-   **Hückstädt, M.** (2023). Determinanten und Effekte von Kooperation in Homogenen und Heterogenen Forschungsverbünden (DEKiF). Daten- und Methodenbericht des DEKiF-Websurveys. Version 1.0.0. Hannover: fdz.DZHW. Hannover.

-   **Hückstädt, M.**, İkiz-Akıncı, D. & Kleimann, B. (2020). Leistungsbewertung in Berufungsverfahren. Traditionswandel in der Akademischen Personalselektion. Daten- und Methodenbericht zur qualitativen Erhebung der DZHW-Studie LiBerTas 2016. Version 1.0.0. Hannover: fdz.DZHW. doi:10.21249/DZHW:lib2016:1.0.0
