---
title: "Recent articles"
listing:
  contents: posts
  sort: "date desc"
  fields: [title, subtitle, reading-time, categories, description, author, date]
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
---

The blog *Chernoff faces* documents knowledge that is more or less loosely connected to my research activities or PhD. These can be both methodological and purely technical. The main purpose of the documentation is to briefly and clearly document knowledge elements that have already been developed for me personally. A very welcome side effect would be if this documentation of mine made it easier for third parties to work with R, Python, SQL etc. or to understand the application of specific methods. To this purpose, tutorials written in Quartmarkdown are regularly published on the blog, in which various data science technics and software packages are applied. To illustrate this, simple questions are practically worked on methods from frequentist and Bayesian statistics.

------------------------------------------------------------------------
