---
title: "Software"
slide-format: revealjs
toc: true
toc-depth: 5
---

## Themes

### DZHW Quarto Revealjs Theme

You can create [Quarto Presentations](https://quarto.org/docs/presentations/) with the [Revealjs](https://quarto.org/docs/presentations/revealjs/) format in the applicable DZHW style. The best way to get a feel for the possibilities of Revealjs is to watch this demo presentation:

<div>

```{=html}
<iframe class="slide-deck" src="https://maltehueckstaedt.github.io/dzhw_revealjs_template/#/title-slide"></iframe>
```

</div>

If you prefer to view the demo in a standalone browser you can do that [here](https://maltehueckstaedt.github.io/dzhw_revealjs_template/#/title-slide). Check out the [source code](https://github.com/maltehueckstaedt/dzhw_revealjs_template/blob/main/template.qmd) for the demo to see how the slides were created.

#### How to install

In the terminal, navigate to the desired working directory. The DZHW-[Quarto](https://quarto.org) theme can then be installed with the following command in the terminal:

``` bash
quarto install extension maltehueckstaedt/dzhw_revealjs_template
```

If you are unable to install Quarto extensions, you probably should [update Quarto](https://quarto.org/docs/get-started/).

#### How to use it

After you install the template, use the following code on terminal to create a new directory with all files needed:

``` bash
quarto use template maltehueckstaedt/dzhw_revealjs_template
```

``` bash
Quarto templates may execute code when documents are rendered. If you do not 
trust the authors of the template, we recommend that you do not install or 
use the template.
```

``` bash
 ? Do you trust the authors of this template (Y/n) › Yes
 ? Directory name: › WRITE/THE/DIRECTORY/HERE/talk/
```

``` bash
[✓] Downloading
[✓] Unzipping
    Found 1 extension.
[✓] Copying files...

Files created:
 - LICENSE.md
 - test2.qmd
 - index.html
 - images
 - quarto-dzhw-theme.Rproj
 - actors.js
 - _extensions
 - clean_title_page.html
 - template.html
 - bibliography.bib
```

## ShinyApps

### Locate Your Cluster!

With the ShinyApp "[Locate Your Cluster](https://chernofffaces.shinyapps.io/Shiny-Collaborations/)" you can check the functionality of your research collaboration in five functionality dimensions (Difference, Relationship, Commitment, Communication, Fairness) and compare your team with other research clusters. The reference point for your data is the information provided by approximately 5000 PIs and spokespersons of DFG research collaborations. Have Fun!

### **Power in the Field of Art School Professors** 

The ShinyApp "[*Power in the Field of Art School Professors*](https://chernofffaces.shinyapps.io/field_of_art_professors_supp_materials/)**"** offers you additional information on the analyses and data of the article "Power in the Field of Art School Professors: The Role of Symbolic, Social, Cultural and Economic Capital" (under review). In this ShinyApp, four tabs are provided:

1.  Cloud of the art schools

2.  Positions of the Professors

3.  Distribution of the inputvariables

4.  Inputdata

Each tab is accompanied by information and instructions. The ShinyApp is thus simple and extremely intuitive to use.
